#!/usr/bin/env python3
"""Generate per-service docker-compose.yml, .env, and systemd unit files.

For each service required by the robot model, this script creates:
  - <output_dir>/<service>/docker-compose.yml  (from compose fragment)
  - <output_dir>/<service>/.env                (image reference + model info)
  - /lib/systemd/system/<service>-container.service  (systemd unit)

Services not required by the model are cleaned up (unit disabled + files removed).

Usage:
    python3 generate_config.py \
        --model <ROBOT_MODEL> \
        --models-yaml /etc/container-runner/models.yaml \
        --compose-dir /usr/lib/container-runner/compose \
        --output-dir /etc/container-runner
"""

from __future__ import annotations

import argparse
import glob
import os
import shutil
import sys
from pathlib import Path

import yaml

SYSTEMD_UNIT_DIR = "/lib/systemd/system"
UNIT_SUFFIX = "-container"


def load_models_yaml(path: str) -> dict:
    """Load and validate the models.yaml configuration file."""
    with open(path, "r") as f:
        config = yaml.safe_load(f)

    required_keys = ["bart_registry", "images", "models"]
    for key in required_keys:
        if key not in config:
            print(f"ERROR: Missing required key '{key}' in {path}", file=sys.stderr)
            sys.exit(1)

    return config


def get_model_config(config: dict, model: str) -> dict:
    """Get configuration for a specific robot model."""
    models = config.get("models", {})
    if model not in models:
        available = ", ".join(sorted(models.keys()))
        print(
            f"ERROR: Unknown robot model '{model}'. Available models: {available}",
            file=sys.stderr,
        )
        sys.exit(1)

    return models[model]


def resolve_image_ref(
    config: dict, model_config: dict, service_name: str
) -> str:
    """Resolve the full image reference for a service.

    Applies per-model image_overrides if present, otherwise uses defaults.
    Format: <registry>/<service>:<tag>@<digest>
    """
    registry = config["bart_registry"]
    default_image = config["images"].get(service_name, {})

    tag = default_image.get("tag", "latest")
    digest = default_image.get("digest", "")

    # Apply per-model overrides if available
    overrides = model_config.get("image_overrides", {}).get(service_name, {})
    if "tag" in overrides:
        tag = overrides["tag"]
    if "digest" in overrides:
        digest = overrides["digest"]

    # Build image reference
    image_ref = f"{registry}/{service_name}:{tag}"
    if digest:
        image_ref = f"{registry}/{service_name}:{tag}@{digest}"

    return image_ref


# Map service names to environment variable names used in compose fragments
SERVICE_ENV_MAP = {
    "rise": "RISE_IMAGE",
    "rise-dashboard": "RISE_DASHBOARD_IMAGE",
    "whole-body-controller": "WHOLE_BODY_CONTROLLER_IMAGE",
}


def generate_service_env(
    config: dict, model_config: dict, model: str, service: str, service_dir: str
) -> None:
    """Generate .env file for a single service."""
    env_path = os.path.join(service_dir, ".env")

    env_key = SERVICE_ENV_MAP.get(service, f"{service.upper().replace('-', '_')}_IMAGE")
    image_ref = resolve_image_ref(config, model_config, service)

    with open(env_path, "w") as f:
        f.write("# Auto-generated by container-runner setup\n")
        f.write(f"# Service: {service}\n")
        f.write("# Do not edit manually - regenerated on package install/upgrade\n\n")
        f.write(f"ROBOT_MODEL={model}\n")
        f.write(f"BART_REGISTRY={config['bart_registry']}\n")
        f.write(f"{env_key}={image_ref}\n")

    print(f"  Generated .env at {env_path}")


def generate_service_compose(
    service: str, compose_dir: str, service_dir: str
) -> bool:
    """Copy compose fragment as the service's docker-compose.yml.

    Returns True if the fragment was found and copied, False otherwise.
    """
    fragment_path = os.path.join(compose_dir, f"{service}.yml")
    if not os.path.exists(fragment_path):
        print(
            f"  WARNING: Compose fragment not found: {fragment_path}, skipping",
            file=sys.stderr,
        )
        return False

    output_path = os.path.join(service_dir, "docker-compose.yml")
    shutil.copy2(fragment_path, output_path)

    print(f"  Generated docker-compose.yml at {output_path}")
    return True


def generate_systemd_unit(service: str, output_dir: str) -> str:
    """Generate a systemd unit file for a single service.

    Returns the unit file name.
    """
    unit_name = f"{service}{UNIT_SUFFIX}.service"
    unit_path = os.path.join(SYSTEMD_UNIT_DIR, unit_name)
    service_dir = os.path.join(output_dir, service)

    env_file = os.path.join(service_dir, ".env")
    compose_file = os.path.join(service_dir, "docker-compose.yml")

    unit_content = f"""\
[Unit]
Description=Container Runner - {service}
Documentation=https://github.com/SamsungHumanoid/container-runner
After=docker.service network-online.target
Requires=docker.service
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory={service_dir}
ExecStartPre=/usr/bin/docker compose --env-file {env_file} -f {compose_file} pull --quiet
ExecStart=/usr/bin/docker compose --env-file {env_file} -f {compose_file} up -d
ExecStop=/usr/bin/docker compose --env-file {env_file} -f {compose_file} down
ExecReload=/usr/bin/docker compose --env-file {env_file} -f {compose_file} up -d
TimeoutStartSec=600
TimeoutStopSec=120

[Install]
WantedBy=multi-user.target
"""

    with open(unit_path, "w") as f:
        f.write(unit_content)

    print(f"  Generated systemd unit at {unit_path}")
    return unit_name


def cleanup_stale_services(active_services: list[str], output_dir: str) -> None:
    """Remove systemd units and config dirs for services no longer needed."""
    # Find existing *-container.service files
    pattern = os.path.join(SYSTEMD_UNIT_DIR, f"*{UNIT_SUFFIX}.service")
    existing_units = glob.glob(pattern)

    active_unit_names = {f"{s}{UNIT_SUFFIX}.service" for s in active_services}

    for unit_path in existing_units:
        unit_name = os.path.basename(unit_path)
        if unit_name not in active_unit_names:
            # Extract service name from unit name
            service = unit_name.replace(f"{UNIT_SUFFIX}.service", "")
            print(f"  Cleaning up stale service: {service}")

            # Remove unit file
            os.remove(unit_path)
            print(f"    Removed {unit_path}")

            # Remove service config directory
            service_dir = os.path.join(output_dir, service)
            if os.path.isdir(service_dir):
                shutil.rmtree(service_dir)
                print(f"    Removed {service_dir}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate per-service docker-compose.yml, .env, and systemd units"
    )
    parser.add_argument(
        "--model",
        required=True,
        help="Robot model name (from ROBOT_MODEL in /etc/environment)",
    )
    parser.add_argument(
        "--models-yaml",
        required=True,
        help="Path to models.yaml configuration file",
    )
    parser.add_argument(
        "--compose-dir",
        required=True,
        help="Path to directory containing compose fragment files",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Output directory for generated per-service configs",
    )
    args = parser.parse_args()

    # Validate paths
    if not os.path.exists(args.models_yaml):
        print(f"ERROR: models.yaml not found: {args.models_yaml}", file=sys.stderr)
        sys.exit(1)

    if not os.path.isdir(args.compose_dir):
        print(
            f"ERROR: Compose directory not found: {args.compose_dir}", file=sys.stderr
        )
        sys.exit(1)

    # Load configuration
    config = load_models_yaml(args.models_yaml)
    model_config = get_model_config(config, args.model)
    services = model_config.get("services", [])

    print(f"Configuring container-runner for robot model: {args.model}")
    print(f"Required services: {', '.join(services)}")

    # Ensure systemd unit directory exists
    Path(SYSTEMD_UNIT_DIR).mkdir(parents=True, exist_ok=True)

    # Generate per-service configs
    configured_services = []
    for service in services:
        print(f"\n[{service}]")

        # Create service directory
        service_dir = os.path.join(args.output_dir, service)
        Path(service_dir).mkdir(parents=True, exist_ok=True)

        # Generate docker-compose.yml from fragment
        if not generate_service_compose(service, args.compose_dir, service_dir):
            continue

        # Generate .env with image reference
        generate_service_env(config, model_config, args.model, service, service_dir)

        # Generate systemd unit file
        generate_systemd_unit(service, args.output_dir)

        configured_services.append(service)

    # Clean up services that are no longer needed
    print("\n[cleanup]")
    cleanup_stale_services(configured_services, args.output_dir)

    print(f"\nConfiguration complete. Enabled services: {', '.join(configured_services)}")


if __name__ == "__main__":
    main()
